package.json
src/components/ToolTip/ToolTip.vue
src/stories/ToolTip.stories.js

Revert "fix(tooltip) add fixed position to tooltip"

---

package.json
src/components/UploadArea/UploadArea.vue

Feat: upload components

---

package.json
src/components/Select/Select.vue

- New valueLabel prop to manually set the select label if necesary
- lint

Feat: Optional value label for Select

---

package.json
src/components/AudioRecorder/AudioHandler.vue
src/components/AudioRecorder/AudioPlayer.vue
src/components/AudioRecorder/AudioRecorder.vue
src/stories/AudioRecorder.stories.js

**Improving the audio component:**
- Added milliseconds at the time of recording
- Added controllable audio progress bar
- Fixed bug when discarding audio and recording a new one
- Refactored the component
- Adjusted some styles

New Audio Recorder

---

package.json
src/components/Input/BaseInput.vue
src/components/Input/Input.vue
src/components/Input/TextInput.vue

**Input default:**
- Changed the caret color
- Fixed placeholder without focus
**Input error:**
- Changed the input and error message colors to red
**Input disabled:**
- Removed the dashed border
-  Changed the placeholder color
-  Changed icons colors

Input refactoring

---

src/components/Modal/Modal.vue
src/stories/Modal.stories.js

feat: added modal mobile version

---

src/components/SelectSmart/SelectSmart.vue
src/stories/SelectSmart.stories.js

- Added orderedByIndex option to not sort the options alphabetically
- Dropdown position fixed to not more scroll together with page

SelectSmart ordered by index and fixed dropdown position

---

src/components/AudioRecorder/AudioRecorder.vue
src/components/ChatsContact/ChatsContact.vue
src/components/ChatsHeader/ChatsHeader.vue
src/components/ChatsMessage/ChatsMessage.vue
src/components/ChatsMessage/ChatsMessageStatusBackdrop.vue
src/stories/ChatsContact.stories.js
src/stories/ChatsHeader.stories.js
src/stories/ChatsMessage.stories.js

- Fixed number of characters in ChatsMessage minutes
- Added avatar and title click events on ChatsHeader
- Added checkbox variation in ChatsContact
- Fixed time of AudioRecorder when the audio is listened completely

Fixed ChatsHeader, ChatsMessage, AudioRecorder and incremented variation in ChatsContact

---

src/components/ChatsMessage/ChatsMessage.vue
src/components/ChatsMessage/ChatsMessageStatusBackdrop.vue

- Adjusted medias border radius
- Fixed backdrop icon size
- Replaced the font of time to 12px

Chats components styles

---

src/components/ButtonClose/ButtonClose.vue
src/components/ChatsHeader/ChatsHeader.vue
src/stories/ChatsHeader.stories.js

Adjusted ChatsHeader to resize by container instead viewport

Chats header resize

---

src/components/ChatsContact/ChatsContact.vue
src/components/ChatsMessage/ChatsMessage.vue
src/stories/ChatsMessage.stories.js

- Adjusted ChatsContact username font weight to bold
- Implemented ChatsMessage text line break and remove html dangerous to text

Fixed ChatsMessage and ChatsContact

---

src/components/Button/Button.vue
src/stories/Button.stories.js

**Goal:** With the aim of smoothing the transition of new buttons on the platform, avoiding highly impactful changes, the solution was devised to refactor the button, but adjust its types so that the new ones were aligned with the previous ones.
- Merged ButtonNext to Button
- Adjusted Button types to fit in with previous styles
- FIxed Button secondary border to inset

Fix of Button types

---

src/components/FormElement/FormElement.vue

Added fixed label in form element to attend this variation:

feat: added fixed label prop variation in form element

---

src/components/ChartBar/ChartBar.vue
src/components/DatePicker/DatePicker.vue
src/components/ModalNext/ModalNext.vue
src/components/ModalUpload/ModalUpload.vue
src/components/Pagination/Pagination.vue
src/stories/ButtonNext.stories.js
src/stories/Comment.stories.js

Fixed the "terciary" type to "tertiary" in all components that import this button variation

Adjusted all components button tertiary types

---

src/components/SelectSmart/SelectSmart.vue
src/components/SelectSmart/SelectSmartMultipleHeader.vue

- Adjusted the value of the selected option after the variable passed by v-model is updated in the parent
- Adjusted the alignment of the remaining text of multiple selected options
- Adjusted the "disabled" variation border for interior
- Adjusted the placeholder color

Fix SelectSmart

---

src/components/ChatsMessage/ChatsMessage.vue
src/stories/ChatsMessage.stories.js

Implementation of link handling in messages, allowing links sent and received to now be clickable and direct to their respective pages.

ChatsMessage treat links

---

src/components/ChatsMessage/ChatsMessage.vue
src/components/ChatsMessage/ChatsMessageText.vue
src/stories/ChatsMessage.stories.js

Goal: Add optional subscription to ChatsMessage
- Componentized ChatsMessageText
- Implemented message signature variation
("Luana", as an example, would be the additional signature)

ChatsMessage signature variation

---

src/components/ChatsContact/ChatsContact.vue
src/components/ChatsUserAvatar/ChatsUserAvatar.vue
src/stories/ChatsContact.stories.js

Goal: Add the variation to the ChatsContact component to contemplate a discussion

ChatsContact of discussion

---

src/components/ChatsHeader/ChatsHeader.vue

Goal: Create a prop to manually control the responsiveness of the ChatsHeader component

ChatsHeader size forced

---

src/components/ChatsContact/ChatsContact.vue
src/components/ChatsUserAvatar/ChatsUserAvatar.vue
src/components/TransitionRipple/TransitionRipple.vue

**Updates:**
1. Fixed the "ripple" transition when clicking on _ChatsContact_, which initially had zero height and width.
2. Forced the first character of _ChatsUserAvatar_ to be capitalized.

Fixed ChatsContact design

---

src/components/Button/Button.vue
src/stories/Button.stories.js

**Updates:**
1. Fixed new icons size at Button
2. Added 'filled' variation of the icon at Button

Button new icons

---

src/components/ChartMultiLine/ChartMultiLine.vue
src/components/ChartMultiLine/Line/Line.vue
src/components/ChatsMessage/ChatsMessage.vue
src/components/IconLoading/IconLoading.vue
src/components/index.js

Feat: ChartMultiLine

---

src/components/Comment/Comment.vue
src/stories/Comment.stories.js

- Migrate unnnic comment into Vue3 compatibility

feat: unnnic comment vue3 migration

---

src/components/ChartMultiLine/ChartMultiLine.vue

Fix: position chart line

---

src/components/ChartMultiLine/ChartMultiLine.vue
src/components/ChartMultiLine/Line/Line.vue

Fix: duplicated keys - chart multi line

Fix: duplicated keys - chart multi line

---

src/components/ChartMultiLine/ChartMultiLine.vue
src/components/ChartMultiLine/Line/Line.vue

Fix: horizontal lines position + add reference values

Fix: horizontal lines position + add reference values

---

src/components/ChartMultiLine/ChartMultiLine.vue
src/components/ChartMultiLine/Line/Line.vue

Fix: svg and tooltip

---

src/components/AvatarIcon/AvatarIcon.vue
src/components/ChartMultiLine/ChartMultiLine.vue

Feat: avatar-icon adjustments for integrations-discovery

Feat: avatar-icon adjustments for integrations-discovery

---

src/components/ChartMultiLine/ChartMultiLine.vue

Fix: chart multi line reference values

Fix: chart multi line reference values

---

src/components/ChartMultiLine/ChartMultiLine.vue

Feat: grand totals - chart multi line

Feat: grand totals - chart multi line

---

src/components/Button/Button.vue
src/stories/Button.stories.js

Related to #459 updates on Vue 3.

feat: added attention type button variation

---

src/components/ChatsNavbar/ChatsNavbar.vue
src/stories/ChatsNavbar.stories.js

**Updates:**
- Added automation for fill icons and accepting icon by string
- Link handler re-made, now externally

Chats Navbar: Updated link handler and automate fill icons

---

src/components/Button/Button.vue
src/stories/Button.stories.js

**Updates:**
- Button float variation

Button float variation

---

src/stories/Alert.stories.js
src/utils/call.js

**Updates:**
- Added container reference parameter for the alert to follow instead of the body

Component Alert: Added container reference parameter to follow instead of the body

---

src/assets/scss/colors.scss

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
The design chapter saw the need for these colors to be changed.
Changed the brand weni colors to within the palette established by the design.

Change brand weni colors

---

package.json
src/components/Alert/AlertBanner.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When trying to upgrade to develop he complained about a component with lint longer than 100 characters on a line
Format

[Nexus 831] - Fix format banner alert variation

---

src/components/TextArea/TextArea.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
old: ![image](https://github.com/weni-ai/unnnic/assets/34746557/3a45aa7c-2233-48b9-9bcf-6c4571a41b56)
new:

[NEXUS-1058] adjusting placeholder color

---

src/components/Slider/Slider.vue

* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
- Update componente to match new design figma
- Adjusting styles
- Logic html structure
- [Design File](https://www.figma.com/design/YbvOpVPUBxTSEzg4J8pXKu/Weni---unnnic?node-id=20167%3A6229&t=VpNNYcU81KuOBqhd-1)

[NEXUS-1223] Update design unnnic Slider

---

package.json
src/components/Slider/Slider.vue
src/components/ToolTip/ToolTip.vue

* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
- Adjusting slider component to match figma
- add label variant
- add labelInfo variant
- add showInputValue variant
- [Design](https://www.figma.com/design/YbvOpVPUBxTSEzg4J8pXKu/Weni---unnnic?node-id=20167%3A6229&t=VpNNYcU81KuOBqhd-1)

[Nexus-1223] update design no unnnic slider component

---

src/components/Tab/Tab.vue
src/stories/Tab.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
The Tab component needed a new variation with tooltip and adjustments to its styling.
- Adjusted Tab styles;
- Added tooltip variation to Tab component;
- Adjusted Tab story to adapt to the new variation.
- [Tab component](https://www.figma.com/design/YbvOpVPUBxTSEzg4J8pXKu/Weni---unnnic?node-id=4063%3A16336)

[ENGAGE-943] - Tab adjusts

---

src/components/index.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
It's need export the Disclaimer and Drawer components in the file that exports the list components.
Added the Disclaimer and Drawer components when exporting the components/index.js file

[ENGAGE-979] - Export Disclaimer and Drawer

---

src/components/index.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
It's need export the Disclaimer and Drawer components in the file that exports the list components.
Added the Disclaimer and Drawer components when exporting the components/index.js file

 [ENGAGE-979] - Export Disclaimer and Drawer (Vue 3)

---

src/components/Icon.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Icon click not emit $event

[ENGAGE-1031] - Fix icon click

---

src/components/DatePicker/DatePicker.vue
src/components/DatePicker/translations.js
src/stories/DatePicker.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
The DatePicker component was missing translations following i18n.
Added translations to DatePicker and removed story fixed texts.

[ENGAGE-1065] - DatePicker translations

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
1.24.21
Package version and changelog.

 [ENGAGE-1109] - 1.24.21

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
2.0.24
Package version and changelog.

 [ENGAGE-1109] - 2.0.24

---

src/components/Slider/Slider.vue

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Fixed a bug in the tooltip when passing the initial value in the slider
- adjust logic to get width data

[NEXUS-1429] - Slider tooltip position error with initialValue

---

src/components/Modal/Modal.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Chats Vue3 Migration
* Fix slots check

[ENGAGE-1088] - Fix modal slots checks

---

.github/workflows/build-unnnic-push-tag-shared.yaml
.github/workflows/npm-publish-pre-release.yaml
.github/workflows/npm-publish.yaml
CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [X] Other
- update develop with main
- update develop with main

Update develop with main

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [X] Other
- update version and changelog vue3
- update version and changelog vue3

Update changelog version vue3

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [X] Other
- update version and changelog
- update version and changelog

Update version and changelog vue2

---

src/components/ModalNext/ModalNext.vue
src/stories/ModalNext.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Migrate of ModalNext to Vue 3
Imported from main the ModalNext component and story and fixed code deprecations to work in vue 3

[ENGAGE-1113] - Migrated ModalNext to Vue 3

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.0.26
Package version and changelog.

[ENGAGE-1113] - 2.0.26

---

src/components/Alert/Alert.vue
src/components/index.js
src/stories/Alert.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
* Exports UnnnicAlert component.

 [Nexus-1566] Unnnic Alert Adjustments

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
* Exports `UnnnicAlert` component.

[Nexus-1566] 2.0.31

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.2.0
- Updated CHANGELOG.md

 [ENGAGE-1260] - 2.2.0

---

.storybook/DocsTemplate.mdx
.storybook/preview.js
src/components/Button/Button.vue
src/stories/Button.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Standardization of stories in Unnnic.
- Added auto docs template to stories;
- Fixed button props defaults;
- Usage autodocs at Button story and improve it.

[ENGAGE-1242] - Story docs template

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.3.0
- Updated CHANGELOG.md

[ENGAGE-1242] - 2.3.0

---

src/components/ModalDialog/ModalDialog.vue
src/stories/ModalDialog.mdx
src/stories/ModalDialog.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds `leftSidebar` slot to ModalDialog for fixed left sidebar content.
- [Brain - Ações v2](https://www.figma.com/design/QE22CBVh18ORmxe1HhDUkD/Brain?node-id=2053-3059&t=EiD70WFEf0lFFzJ9-4)

[Nexus-1670] Modal Dialog: Left Sidebar Slot

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.3.1
* Changes CHANGELOG.md.

[Nexus-1670] - 2.4.0

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.5.0

[ENGAGE-1353] - 2.5.0

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.6.1

[ENGAGE-1245] - 2.6.1

---

src/components/Tour/Tour.vue
src/components/Tour/TourMask.vue
src/components/Tour/TourPopover.vue
src/components/Tour/propsValidation.js
src/components/index.js
src/stories/Tour.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
A tour component was needed to create the Insights module's guided tour.
- Created the Tour component;
- Added the Tour story;
- Exported the Tour component.
- [Insights guided tour](https://www.figma.com/design/P9yyN4D0wGMlzYMjOtHvv3/Insights?node-id=5681-9541&t=opSDG8v7YE3YEITU-0)

[ENGAGE-1439] - Tour component

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.7.0

[ENGAGE-1439] - 2.7.0

---

src/components/DropArea/DropArea.vue
src/components/ImportCard/ImportCard.vue
src/components/UploadArea/UploadArea.vue
src/stories/DropArea.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Separates `DropArea` from `UploadArea` so that they can be used independently;
* Updates  the `ImportCard` design.

[Nexus-1782] Vue2: Update Upload Area Design

---

CHANGELOG.md
package.json
src/components/index.js

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 1.25.0
* Separates `DropArea` from `UploadArea` so that they can be used independently;
* Updates  the `ImportCard` design.
See more in #541.

[Nexus-1782] Release: 1.25.0

---

src/components/DropArea/DropArea.vue
src/components/ImportCard/ImportCard.vue
src/components/UploadArea/UploadArea.vue
src/components/index.js
src/stories/DropArea.mdx
src/stories/DropArea.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Separates `DropArea` from `UploadArea` so that they can be used independently;
* Updates  the `ImportCard` design.

[Nexus-1782] Vue3: Update Upload Area Design

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 1.25.0
* Separates `DropArea` from `UploadArea` so that they can be used independently;
* Updates  the `ImportCard` design.
See more in #541.

[Nexus-1782] Release: 2.8.0

---

src/components/Sidebar/SidebarItem.vue

* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
- Improve personalization icons
- adding new variable iconFilled

[NEXUS-1862] - add variable iconFilled - SidebarItem

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [X] Other
Release 2.8.2 version

[NEXUS-1862] - Release 2.8.2

---

src/components/EmojiPicker/EmojiPicker.vue
src/stories/EmojiPicker.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Some contexts require the EmojiPicker to open downwards compared to its container.
- Added EmojiPicker position bottom variation
- Refactored EmojiPicker story and added PositionBottom variation
https://github.com/user-attachments/assets/ec15b7a3-8cf9-4d2c-940b-820d9e09ca83

[ENGAGE-1513] - EmojiPicker position bottom variation

---

src/components/Radio/Radio.vue
src/components/Radio/__test__/Radio.spec.js
src/components/Radio/__test__/__snapshots__/Radio.spec.js.snap
src/components/Tab/Tab.vue
src/components/Tab/__test__/Tab.spec.js
src/components/Tab/__test__/__snapshots__/Tab.spec.js.snap

* * [ ] Bugfix
* * [X] Tests
* * [ ] Other

[CFE-316] - Radio and Tabs tests

---

src/components/Input/BaseInput.vue
src/components/Input/Input.vue
src/components/Input/TextInput.vue
src/components/Input/__test__/BaseInput.spec.js
src/components/Input/__test__/Input.spec.js
src/components/Input/__test__/__snapshots__/BaseInput.spec.js.snap

* * [ ] Bugfix
* * [X] Tests
* * [ ] Other

[NEXUS-1921] - Add Input tests

---

src/components/Input/__test__/Input.spec.js
src/components/TextArea/TextArea.vue
src/components/TextArea/__test__/TextArea.spec.js
src/components/TextArea/__test__/__snapshots__/TextArea.spec.js.snap

* * [ ] Bugfix
* * [X] Tests
* * [ ] Other

[NEXUS-1956] - TextArea Tests

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.13.0

[CFE-357] - 2.13.0

---

src/components/AvatarIcon/__tests__/AvatarIcon.spec.js

* * [ ] Bugfix
* * [X] Tests
* * [ ] Other

[CFE-323] - add avatar icon tests

---

src/components/Pagination/Pagination.vue
src/components/Pagination/__tests__/Pagination.spec.js

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Adds test for `Pagination.vue` component.

[Nexus-2038] Test: Pagination.vue

---

src/components/Alert/Alert.vue
src/components/Alert/AlertBanner.vue
src/components/Alert/Version1dot1.vue
src/components/Alert/__tests__/Alert.spec.js
src/components/Alert/__tests__/AlertBanner.spec.js
src/components/Alert/__tests__/AlertCaller.spec.js
src/components/Alert/__tests__/Version1dot1.spec.js

* * [ ] Bugfix
* * [X] Tests
* * [ ] Other

[CFE-341] - Add Alert tests

---

src/components/TextArea/TextArea.vue
src/stories/Input.mdx
src/stories/Input.stories.js
src/stories/SelectSmart.mdx
src/stories/SelectSmart.stories.js
src/stories/TextArea.mdx
src/stories/TextArea.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
To exemplify the uses of Input and Textarea, and the error state in SelectSmart, stories have been created for them.
* Fixes `min-height` of the textarea to md and sm sizes;
* Adds stories for Input and TextArea components;
* Adds Error story for SelectSmart.

[RS-181] Docs for Input and Textarea and Error Story for SelectSmart

---

src/components/AudioRecorder/AudioRecorder.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Audio duration at audio recorder is Infinity.
- Added function to bypass chrome audio duration

[NEXUS-2126] - Fix audio duration

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.13.1

[NEXUS-2126] - 2.13.1

---

src/components/TableNext/TableBodyCell.vue
src/components/TableNext/TableNext.vue
src/components/TableNext/TablePagination.vue
src/components/TableNext/__test__/TableBodyCell.spec.js
src/components/TableNext/__test__/TableNext.spec.js
src/components/TableNext/__test__/TablePagination.spec.js
src/components/TableNext/__test__/__snapshots__/TableNext.spec.js.snap
src/components/TableNext/__test__/__snapshots__/TablePagination.spec.js.snap
src/components/TableNext/__test__/validation.unit.test.js
src/mixins/i18n.js
src/utils/plugins/i18n.js
yarn.lock

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Improve and maintain components coverage
- Fixed i18n mixin vue 3 inconsistencies;
- Added TablePagination, TableBodyCell e TableNext tests.

[CFE-383] - TableNext tests

---

package.json
src/components/SelectSmart/SelectSmart.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Allow an empty option for autocomplete.
Identify empty newOption on onSelectOption method.

[RS] - Fix: Select Smart empty option

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.14.2 version

[CFE-472] - 2.14.2

---

src/components/ModalDialog/ModalDialog.vue
src/components/ModalDialog/__tests__/ModalDialog.spec.js
src/components/ModalDialog/__tests__/__snapshots__/ModalDialog.spec.js.snap

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Increase test coverage in Unnnic
- Added tests for ModalDialog.

[CFE-359] - ModalDialog tests

---

src/components/Drawer/Drawer.vue
src/components/Drawer/__tests__/Drawer.spec.js
src/components/Drawer/__tests__/__snapshots__/Drawer.spec.js.snap

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Increase test coverage in Unnnic
- Added tests for Drawer.

[CFE-359] - Drawer tests

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.15.0

[NEXUS-2204] - 2.15.0

---

src/components/SelectSmart/SelectSmart.vue
src/components/SelectSmart/SelectSmartMultipleHeader.vue
src/components/SelectSmart/SelectSmartOption.vue
src/components/SelectSmart/__tests__/SelectSmart.spec.js
src/components/SelectSmart/__tests__/SelectSmartMultipleHeader.spec.js
src/components/SelectSmart/__tests__/SelectSmartOption.spec.js
src/components/SelectSmart/__tests__/__snapshots__/SelectSmartMultipleHeader.spec.js.snap
src/components/SelectSmart/__tests__/__snapshots__/SelectSmartOption.spec.js.snap

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Increase test coverage in Unnnic
- Added initial tests for SelectSmart, covering 85% of the component.

[CFE-426] - Some SelectSmart tests

---

src/components/ChartFunnel/ChartFunnel.vue
src/components/ChartFunnel/DefaultFunnel/ChartDefaultFunnelBase.vue
src/components/ChartFunnel/DefaultFunnel/__tests__/ChartDefaultFunnelBase.unit.spec.js
src/components/ChartFunnel/DefaultFunnel/__tests__/__snapshots__/ChartDefaultFunnelBase.unit.spec.js.snap
src/components/ChartFunnel/SvgFunnel/ChartFunnelBaseRow.vue
src/components/ChartFunnel/SvgFunnel/__tests__/ChartFunnelBaseRow.unit.spec.js
src/components/ChartFunnel/SvgFunnel/__tests__/ChartFunnelFiveRows.unit.spec.js
src/components/ChartFunnel/SvgFunnel/__tests__/ChartFunnelFourRows.unit.spec.js
src/components/ChartFunnel/SvgFunnel/__tests__/ChartFunnelThreeRow.unit.spec.js
src/components/ChartFunnel/SvgFunnel/__tests__/__snapshots__/ChartFunnelBaseRow.unit.spec.js.snap
src/components/ChartFunnel/SvgFunnel/__tests__/__snapshots__/ChartFunnelFiveRows.unit.spec.js.snap
src/components/ChartFunnel/SvgFunnel/__tests__/__snapshots__/ChartFunnelFourRows.unit.spec.js.snap
src/components/ChartFunnel/SvgFunnel/__tests__/__snapshots__/ChartFunnelThreeRow.unit.spec.js.snap
src/components/ChartFunnel/__tests__/ChartFunnel.unit.spec.js
src/components/ChartFunnel/__tests__/__snapshots__/ChartFunnel.unit.spec.js.snap

* * [ ] Bugfix
* * [X] Tests
* * [ ] Other

[ENGAGE-1956] - Add Chart funnel unit tests 

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.17.0

[NEXUS-2225] - 2.17.0

---

package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
- adding to resolve problem to use shared in module federation
- add new export

[ENGAGE-2051] add new export - package.json

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.18.0

[ENGAGE-2193] 2.18.0

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.21.0
- Update version and changelog

[NEXUS-2590] - 2.21.0

---

src/components/Card/CardStatusesContainer.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- Fix to resolved break in some screens
- add new width to title

[ENGAGE-2849] Fix card statuses container

---

src/components/Modal/Modal.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Preventive undefined style error
- add if at refs

[ENGAGE-2641] Fix undefined style error

---

src/components/SelectSmart/SelectSmart.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- fix undefined error

[ENGAGE-2873] Fix ScrollIntoView

---

src/components/SelectSmart/SelectSmart.vue
src/components/SelectSmart/SelectSmartOption.vue
src/components/SelectSmart/__tests__/SelectSmart.spec.js
src/components/SelectSmart/__tests__/SelectSmartOption.spec.js
src/stories/SelectSmart.stories.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- new variant to select smart
- adding secondary option
- [Design File 1](https://www.figma.com/design/b5K427ZyxboscTyXlqTZOJ/Plataforma-1.5---Home?node-id=373-7007&m=dev)

[ENGAGE-2982] Add new variant select smart

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.24.0

[NEXUS-2683] - 2.24.0

---

CHANGELOG.md
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.28.0

[NEXUS-2803] - 2.28.0

---

CHANGELOG.md
package.json
src/components/DatePicker/DatePicker.vue
src/components/DatePicker/translations.js
src/components/InputDatePicker/InputDatePicker.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
This PR aims to improve the user experience and update the icons to the new ones.
* Updates icons;
* Fixes buttons translations;
* Selects option automatically when the user selects the equivalent dates;
* Prevents the custom option to be selectable (it is only selected when the user selected custom dates).

[HS-1613] DatePicker UX Improvements

---

CHANGELOG.md
package.json
src/components/EmojiPicker/EmojiPicker.vue
src/components/EmojiPicker/__tests__/EmojiPicker.spec.js
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
yarn.lock

* * [ ] Bugfix
* * [X] Feature
* * [x] Code style update (formatting, local variables)
* * [X] Tests
* * [ ] Other
- add new lib emoji picker to fast render and use vue
- change lib emoji to use emoji vue lib
- adjust tests
- refactoring to use ts

[ENGAGE-5146] Feat/change emoji picker lib

---

CHANGELOG.md
src/components/Chip/Chip.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Improvements styles chip component
- adjust styles
- [Design File](https://www.figma.com/design/ZhRJNxJdDxJmZRo15APiKs/Revis%C3%A3o---Unnnic?node-id=886-1452&m=dev)

[ENGAGE-5538] Improvements styles chip component
