- package.json
- src/components/Dropdown/Dropdown.vue
`.stop` will prevent the dropdown click to trigger parent elements `@click` events
> fix: prevent dropdown click trigger parent element clicks

- package.json
- src/components/DatePicker/DatePicker.vue
Firefox does not accept the creation of dates with the string `mm-dd-yyyy` , only chrome.
To fix that all dates are now `mm dd yyyy`, including the incoming props, where the `-` character is manually removed.
> Fix: DatePicker Firefox compatibility

- package.json
- src/components/Input/Autocomplete.vue
Fixed bug that was necessary to have two clicks to close autocomplete options, now just one click to select the option and close the options.
> fix: fixed one click to action in autocomplete option

- src/components/Modal/Modal.vue
- Run lint on the file
- Added condition to show the `modalIcon` container, when it was not provided an empty container was displayed, creating an empty gap between the top of the modal and the title
Before:
After:
> Fix: Modal icon container and lint

- src/components/DatePicker/DatePicker.vue
Solved: Buttons responsible for changing the month that closed the date selector unexpectedly
> Fixed InputDatePicker month change buttons

- src/components/Button/Button.vue
- src/stories/Button.stories.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The button's float variation was with the window reference, but the component's intention is for it to float only in the container and not in the entire window.
Changed the `position` of the float button from `fixed` to `absolute`.
> Fixed the position reference of the float button

- src/components/Alert/Alert.vue
- src/components/Alert/AlertBanner.vue
- src/stories/Alert.stories.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
add a new variation to the alert component
creation of an alert banner with 3 types 'info', 'warning' and 'danger'. Possibility to add links and close button
- [Figma Link](https://www.figma.com/file/YbvOpVPUBxTSEzg4J8pXKu/Weni---unnnic?type=design&node-id=19669%3A5663&mode=design&t=DWjCdsP2kq9G73GF-1)
Final result with variations:
> [Nexus-831] - Add banner alert variation

- src/components/Checkbox/Checkbox.vue
- src/components/Radio/Radio.vue
* * [x] Bugfix
* * [] Feature
* * [ ] Tests
* * [ ] Other
Change from neutral-soft (#E2E6ED) to neutral-cleanest (#D0D3D9). In the Checkbox and Radio components
- [Design](https://www.figma.com/file/YbvOpVPUBxTSEzg4J8pXKu/Weni---unnnic?type=design&node-id=3359-198&mode=design&t=Gju5y9TblKxk3lTk-0)
> [Nexus 848] - Fixed wrong neutral colors in checkbox and radio components

- src/components/Checkbox/Checkbox.vue
- src/stories/Checkbox.stories.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The "less" variation of the checkbox had the wrong behavior, changing, when clicked, from this to "checked" instead of "unchecked".
Added 'less' variation equivalent to 'checked'.
> Fix checkbox less variation

- src/components/Accordion/Accordion.vue
- src/components/Alert/Alert.vue
- src/components/Banner/InfoBanner.vue
- src/components/Button/Button.vue
- src/components/Card/BlankCard.vue
- src/components/Card/ContentCard.vue
- src/components/Card/MarketplaceCard.vue
- src/components/Carousel/TagCarousel.vue
- src/components/Checkbox/Checkbox.vue
- src/components/Flag.vue
- src/components/Icon.vue
- src/components/Modal/Modal.vue
- src/components/Radio/Radio.vue
- src/components/SelectSmart/SelectSmartMultipleHeader.vue
- src/components/Sidebar/SidebarPrimary.vue
- src/components/Switch/Switch.vue
- src/components/Tag/BrandTag.vue
- src/components/Tag/DefaultTag.vue
- src/components/Tag/IndicatorTag.vue
- src/components/UploadArea/UploadArea.vue
- src/stories/Comment.stories.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Some components had the error "Failed to resolve component: UnnnicIcon...", not rendering the necessary icon. The problem was in the way the icon was imported into such components, not following a case pattern (importing as `unnnicIcon` and trying to use it as `UnnnicIcon`, for example).
The import of icons was standardized to `UnnnicIcon`, thus preventing the error from occurring.
> [ENGAGE-912] - Vue 3 import of icons at unnnic components

- src/components/TableNext/TableNext.vue
- src/stories/TableNext.stories.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The interval calculated automatically by `rows.length` generated a bug when the request was on the last page and it did not return the `rows.length` of other requests.
Now, a prop with the pagination interval value is expected. Some lint issues were also adjusted.
> [ENGAGE-1109] - Fix TableNext pagination interval (Vue 3)

- src/components/TableNext/TableNext.vue
- src/stories/TableNext.stories.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The interval calculated automatically by `rows.length` generated a bug when the request was on the last page and it did not return the `rows.length` of other requests.
Now, a prop with the pagination interval value is expected. Some lint issues were also adjusted.
> [ENGAGE-1109] - Fix TableNext pagination interval

- src/components/TableNext/TableNext.vue
- src/components/TableNext/validation.js
- src/stories/TableNext.stories.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
A variation to set the size for each column was necessary for the table on some occasions, as in the demonstration.
- Added the possibility of passing the size for each header;
- Added a size of 0.3 to the ID header of stories;
- Added validation to receive only positive numbers if the header has the "size" field.
Demonstration where the ID header has a size of just 0.3fr of the grid:
> [ENGAGE-1260] - Custom size in TableNext headers

- src/components/Drawer/Drawer.vue
- src/stories/Drawer.stories.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
In some contexts, the drawer is used together with a modal. Therefore, to avoid having two overlays on the screen, the Drawer variation without the overlay was required. Also, in other contexts it makes more sense for the Drawer close icon to be something other than an arrow.
- Added Drawer without overlay variation and its story;
- Fixed close icon of Drawer to be dynamic.
> [ENGAGE-1353] - Drawer without overlay and dynamic icon

- .github/workflows/npm-publish-pre-release.yaml
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The pre-release version was not being created by the workflow due to a conflict in the push on existing tags.
Change in the workflow that creates the pre release to upload only the tag created in the `yarn version`.
> [ENGAGE-1245] - Fix pre-release workflow

- src/components/Drawer/Drawer.vue
- src/stories/Drawer.stories.js
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Some contexts require the separation of the functionalities given to the back button and close the drawer.
The option to separate the "back" and "close" events has been added. Also, the logic for the drawer close transition has been separated in case the context needs more than the event emission after the transition.
https://github.com/user-attachments/assets/a50af34d-eeeb-4bfc-bf3b-a0a7c5dd9490
> [ENGAGE-1513] - Drawer distinct close and back actions

- src/components/TableNext/TableNext.vue
- src/components/TableNext/__test__/TableNext.spec.js
- src/components/TableNext/__test__/__snapshots__/TableNext.spec.js.snap
- src/components/TableNext/__test__/validation.unit.test.js
- src/components/TableNext/validation.js
- src/stories/TableNext.stories.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Add table variations with medium size, no header and "auto" column size.
- Added `hideHeaders` and `size` props;
- Added the possibility of column sizes being 'auto';
- Improved TableNext documentation;
- Removed the requirement to pass the `headers` prop.
> [NEXUS-2170] - TableNext variations

- src/components/Button/Button.vue
- src/components/Button/__tests__/Button.spec.js
- src/components/Drawer/__tests__/__snapshots__/Drawer.spec.js.snap
- src/components/ModalDialog/__tests__/__snapshots__/ModalDialog.spec.js.snap
- src/stories/Button.stories.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
For Agent Builder 2.0, the design required the button icon to be filled.
- Added IconsFilled prop at Button component;
- Add iconsFilled prop test for Button component.
> [NEXUS-2590] - Added IconsFilled prop at Button component

- src/components/Drawer/Drawer.vue
- src/components/Drawer/__tests__/Drawer.spec.js
- src/stories/Drawer.stories.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
For Agent Builder 2.0, the design required the drawer with 66% of width and customized title.
- Added Drawer customized slot title;
- Added giant variation to Drawer;
- Enhance Drawer component test coverage.
> [NEXUS-2590] - Drawer giant size and customized title

- src/components/Tag/Tag.vue
- src/components/Tag/TagNext.vue
- src/stories/Tag.stories.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
To cover some new features, it was necessary to add a new style for the tag component. This PR is only covering a few use cases, such as the weni and purple schema. The idea is that we will later come back to this variation to make it the new version of the Tag component.
Add new initial 'next' type to UnnnicTag component.
- [Design File](https://www.figma.com/design/FGfl8EmJCNMz45TX1s3XQO/Agents-Builder-2.0?node-id=1846-11421&m=dev)
> [NEXUS-2683] - Add new initial 'next' type to UnnnicTag component

- src/components/FormElement/FormElement.vue
- src/components/Input/BaseInput.vue
- src/components/Input/Input.vue
- src/components/Label/Label.vue
- src/components/SelectSmart/SelectSmartOption.vue
- src/components/TextArea/TextArea.vue
- src/stories/TextArea.stories.js
- src/utils/sanitize.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
> [HS - 680] Chore: ensure form components are secure against XSS

- Dockerfile
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The Docker build was failing with a dependency resolution conflict. This caused the build pipeline to fail in the `build-unnnic-push-tag-shared.yaml` workflow, preventing successful Docker image creation and deployment.
Dockerfile Updates: 
- **Changed package manager**: Switched from `npm` to `yarn` to maintain consistency with another workflows (Yarn resolves to compatible versions (@typescript-eslint/parser v8.43.0) while npm attempts to install incompatible versions)
> [CFE-738] - Fix dockerfile build
